
services:
  frontend:
    build:
      context: ./frontend
    env_file:
      - frontend/.env
    depends_on:
      - backend
    ports:
      - '5173:5173'
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    env_file:
      - backend/.env
    ports:
      - '8000:8000'
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - backend/.env
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
       ADMINER_DEFAULT_SERVER: db


networks:
  app-network:
      driver: bridge

